### ISSUE TITLE
Lonewolf Not Loading

### ISSUE THREAD

**Issue by TurbooGhost** [flathub/site.someones.Lonewolf#4]
The app is not loading. 

OS: Debian GNU/Linux 12 (bookworm) x86_64 
Kernel: 6.1.0-12-amd64 
node -v: v18.13.0

![Screenshot from 2023-10-05 17-56-47](https://github.com/flathub/site.someones.Lonewolf/assets/61920916/4e1165ec-9705-4945-b296-e56eb8f88827)

**Comment by aichingm** [comment]
Hi, thanks for your report. This repository is only for managing the flathub build instructions. Could you please open a new issue in the issue tracker at https://GitHub.com/aichingm/Lonewolf!

Thanks!
